services:
  app:
    tty: true
    stdin_open: true
    build:
      context: .
    ports:
      - "3000:3000" 
    volumes:
      - ".:/app"
    environment:
      - RAILS_ENV=development
      - MONGODB_HOST=mongodb
      - OMDB_API_KEY=e415e895 
      - SECRET_KEY=4cdc1333d9ba42282bb739a5478981fe3146aaf3a92ff1789e34d5e564895ba2c447ddc787afd4ccaaa143518b433c3e4162926bd98870fdfd605b07a72cf246
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: