services:
  app:
    tty: true
    stdin_open: true
    build:
      context: .
    ports:
      - "3000:3000" # Mapeia a porta 3000 do container para a porta 3000 do host
    volumes:
      - ".:/app" # Monta o diretório atual no container
    environment:
      - RAILS_ENV=development
      - MONGODB_HOST=mongodb # Nome do serviço do MongoDB
      - OMDB_API_KEY=e415e895 # Substitua pela sua chave da API OMDb
      - SECRET_KEY=4cdc1333d9ba42282bb739a5478981fe3146aaf3a92ff1789e34d5e564895ba2c447ddc787afd4ccaaa143518b433c3e4162926bd98870fdfd605b07a72cf246
    depends_on:
      - mongodb # Garante que o MongoDB seja iniciado antes do app
  mongodb:
    image: mongo:latest # Usa a imagem oficial do MongoDB
    container_name: mongodb
    ports:
      - "27017:27017" # Mapeia a porta 27017 do container para o host
    volumes:
      - mongodb_data:/data/db # Persistência de dados do MongoDB

volumes:
  mongodb_data: