services:
  app:
    tty: true
    stdin_open: true
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    environment:
      RAILS_ENV: development
      MONGODB_HOST: mongodb
      OMDB_API_KEY: ${OMDB_API_KEY} 
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - mongodb
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
